### PR TITLE
Visualization: Scrollbar & Error Message

### PR DESCRIPTION
**Pull request by marcusnovotny**
Working on #71 

This pull adds a horizontal scroll bar (dragging only ™) & error messages when the .csv is missing.

**Known issues**
- The 404 Error of the XMLHttpRequest is still shown in the console and I don't know how to catch it. Wrapping the d3.csv function in a try / catch block didn't work
- Transitions in Firefox 45 seem pretty harsh

### CODE REVIEW

**Comment by sacdallago** [comment]
[Who uses firefox anyway?](http://www.w3schools.com/browsers/browsers_stats.asp) :laughing:

**Comment by sacdallago** [comment]
Ouh and I like the color change! ;)

**Comment by julienschmidt** [comment]
Awesome!

**Comment by julienschmidt** [comment]
And don't worry about the 404, that is impossible to fix / there is nothing to fix. That's the network error for the request which was answered with a 404 which is shown.

**Comment by julienschmidt** [comment]
Maybe using `transform` instead of `x` works better in Firefox.

``` js
d3.selectAll('path').attr("transform", 'translate(' + Number + ', 0)' );

// vs
d3.selectAll('path') .attr('x', Number)
```

Moreover you could  move the whole "canvas" instead of the single elements on the graph.

See also https://css-tricks.com/transforms-on-svg-elements/

**Comment by marcusnovotny** [comment]
Was about to post this:
The time it takes to recalculate & redraw our graph seems to scale linearly in FF and IE while it's consistently low in Chrome. If we're looking at a basically empty graph they all perform smoothly, but a lot of data means chunky rendering atm

I'll look into it!

**Comment by julienschmidt** [comment]
@marcusnovotny but set priorities, get the more important stuff done first. @sacdallago made already clear that he doesn't care so much about FF :wink:

**Comment by sacdallago** [comment]
Was that so obvious? :laughing: IE!?!?!!!! Even Microsoft abandoned that :joy:

**Pull request merged**
