### PR TITLE
Aggregator

### LINKED ISSUE #36: Data Aggregation
We should make a plan how we aggregate the data

Our input is a database with tons of tweets and our output should be CSV data per character and week / day / hour (/ 10/5/1 minutes?)

My idea would be local "buckets" (basically just a multi-dimensional array) where we can easily append data from streamed tweets etc. Any other ideas?

### PR DESCRIPTION
**Pull request by julienschmidt**
Fixes #36

### CODE REVIEW

**Comment by julienschmidt** [comment]
It hurts a bit to remove [this absolutely beautiful code](https://github.com/Rostlab/JS16_ProjectD_Group4/pull/70/commits/f6efae608b94ed2388ffc5772db38c322ad2ff42#diff-d8a29c0e20364a7ca9e04474b3116c9fL93) but I don't think we can serve daily CSV with per-minute precision.

It creates a little too many files and a year has 525600 minutes, the likelihood that 2 tweets are in the same minute is really low. It would have been cool to see the very specific tweets during episodes, but that's a bit too ambitious (for now).

Also the overall CSV and the CSVs per year contain the same information (combined). We should figure out which one we need.
If D3 is capable of displaying the overall CSV without performance issues, we're fine anyway. Otherwise we should filter client-side. The files are not overly large.

**Comment by julienschmidt** [comment]
Aaaaaand the yearly CSV files are gone. Now there are just two precision levels per character:
1. `name.csv`: overall file with values per day (of all years)
2. `name/2016-03.csv`: monthly file with values per hour (of the given month)

If no data for this month / at all exists, the file(s) are not generated. Expect a `404` in that case - or better, don't make the request in the first place.

**Comment by julienschmidt** [comment]
@CavidSalahov :ship: [v0.1.0](https://github.com/Rostlab/JS16_ProjectD_Group4/releases/tag/v0.1.0)

**Comment by jsalahov** [comment]
Done.
@sacdallago Currently auto-deploy configured for master branch only. Can I switch that to develop, so that packages get deployed in time, even when I am not around?

**Comment by sacdallago** [comment]
@CavidSalahov the short answer is: no :laughing: 
The long one: Have you ever seen the difference between stable and unstable releases? In the _normal flow_ master is stable and develop unstable. Master really just represents releases that are meaningful, while develop is much more incremental and, well, unstable.

So please try to stick to this model.

Ideally after FF you merge develop into master and then again only after deadline. But I have been very lean on this ;)

**Comment by jsalahov** [comment]
I know :neutral_face: But we are already publishing packages from develop, 0.1.0 was the 5th release.

**Comment by sacdallago** [comment]
That's why I said:

> But I have been very lean on this ;)

:dancer:

**Pull request merged**
