### PR TITLE
Visualization: Final Adjustments

### PR DESCRIPTION
**Pull request by marcusnovotny**
Finalizing #71 

So far this pull:
- introduces the trendline using a toggle-button
- makes @sacdallago really happy

**Trendline**
On startup

When hovering

In action

### CODE REVIEW

**Comment by marcusnovotny** [comment]
@sacdallago
Is it good practice to use `<foreignObject>`? Makes displaying the error & about message a lot more easy because it allows me to apply automatic line breaks to svg text. It's not supported on IE though, therefore About & Error Text would be empty there :confused: 

[A little more information from caniuse.com](http://caniuse.com/#search=foreign)

**Comment by julienschmidt** [comment]
I have no idea

**Comment by sacdallago** [comment]
@marcusnovotny this is so specific and new that I can't really give you answer - I don't know myself.
I will ask @gyachdav and @dmitry-n to comment.

For me no support on IE is not such a big deal, I believe the age of running behind _way too retarded_ users is over. And who would go on got.show on IE anyway :D

**Comment by gyachdav** [comment]
what would be the alternative in IE? display nothing?

**Comment by marcusnovotny** [comment]
At the moment, yes.

**Comment by gyachdav** [comment]
I believe that a good UI shows users error messages (errors not warnings) no matter how ugly these are presented. showing nothing and still failing in the background is a bad practice in my opinion.

**Comment by julienschmidt** [comment]
23:59, time to merge!
Open another PR if you have something else to be merged :)

**Comment by marcusnovotny** [comment]
:smile: :+1: I'll post the final update tonight

**Comment by julienschmidt** [comment]
@CavidSalahov you know the drill...

**Comment by jsalahov** [comment]
One freshly baked package comping up :smile: 
Btw, remember to bump the version in package.json

**Pull request merged**
