### PR TITLE
Mobile Crawler

### LINKED ISSUE #24: Scraping Twitter mobile site
## 1. Make search

Go to `https://mobile.twitter.com/search?q={character+name}&s=typd&x=13&y=16`, e.g. `https://mobile.twitter.com/search?q=tyrion+lannister&s=typd&x=13&y=16` **with JavaScript disabled** (otherwise a non-static site is served) or just wget / cURL it.
## 2. Extract content

We get a list of tweets. For each tweet there is an entry like the following:

``` html
<table class="tweet  " href="/PrinceSalad1/status/710145884009467904?p=v">
    <tr class="tweet-header ">
        <td class="avatar" rowspan="3">
            <a href="/PrinceSalad1?p=i">
                <img alt="Be The Change!" src="https://pbs.twimg.com/profile_images/693937036697419776/K0f92PDI_normal.jpg" />
            </a>
        </td>
        <td class="user-info">
            <a href="/PrinceSalad1?p=s">
                <strong class="fullname">Be The Change!</strong>
                <div class="username">
                    <span>@</span>PrinceSalad1
                </div>
            </a>
        </td>
        <td class="timestamp">
            <a name="tweet_710145884009467904" href="/PrinceSalad1/status/710145884009467904?p=p">2h</a>
        </td>
    </tr>
    <tr class="tweet-container">
        <td colspan="2" class="tweet-content">
            <div class="tweet-text" data-id="710145884009467904">
                <div class="dir-ltr" dir="ltr"> <span class="twitter-hit-highlight">Tyrion</span> <span class="twitter-hit-highlight">Lannister</span> is the smartest man I have ever seen on TV 😭
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="meta-and-actions">
            <span class="metadata">
        <a href="/PrinceSalad1/status/710145884009467904?p=v">View details</a>
        <span class="middot">&middot;</span>
            </span>
            <span class="tweet-actions">
        <a href="/PrinceSalad1/reply/710145884009467904" class="first">
            <img alt="Reply"   src="https://ma.twimg.com/twitter-mobile/3d969fa99f67efe5d80be77d08a716718f92bfea/images/sprites/tweet_reply.gif">
        </a>
          <a href="/statuses/710145884009467904/retweet">
                <img alt="Retweet"   src="https://ma.twimg.com/twitter-mobile/3d969fa99f67efe5d80be77d08a716718f92bfea/images/sprites/tweet_rt.gif">
          </a>
        <a href="/statuses/710145884009467904/favorite?authenticity_token=386bbbe1ca2cdd2af9e4967bade88dd1" class="favorite">
              <img alt="Like"   src="https://ma.twimg.com/twitter-mobile/3d969fa99f67efe5d80be77d08a716718f92bfea/images/sprites/tweet_heart.gif">
        </a>
        <a href="/PrinceSalad1/status/710145884009467904/actions" class="last"></a>
      </span>
        </td>
    </tr>
</table>
```

Of specific interest is

``` html
            <div class="tweet-text" data-id="710145884009467904">
                <div class="dir-ltr" dir="ltr"> <span class="twitter-hit-highlight">Tyrion</span> <span class="twitter-hit-highlight">Lannister</span> is the smartest man I have ever seen on TV 😭
                </div>
            </div>
```

It contains:
Unique Tweet ID: 710145884009467904
Tweet Text: "Tyrion Lannister is the smartest man I have ever seen on TV 😭"
## 3. Iterate

At the end of the page is a link to older tweets: 

```
        <a href="/search?q=tyrion%20lannister&amp;s=typd&amp;next_cursor=TWEET-706813915489898497-710173609021599744-BD1UO2FFu9QAAAAAAAAETAAAAAcAAAASAAAAAAAAAAAAAAAAAAAAAAAAAgAQAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAA"> Load older Tweets </a>
```

This links seems to be valid forever. We can use those links to iterate.
## Things to figure out
- [x] ~~Is there request limiting?~~ **Nope!** 
- [x] ~~How to easily parse HTML?~~ **Parse?! RegEx!**
- [x] How to clear tweet text from HTML tags?

### PR DESCRIPTION
**Pull request by julienschmidt**
Ladies and Gentlemen, we have a working Twitter Mobile crawler! (See #24)

It scrapes the IDs from the mobile site and then looks up the IDs with the REST API to get all required information. The mobile site is missing e.g. the post dates of the tweets.

Fixes #24

### CODE REVIEW

**Comment by gyachdav** [comment]
You rock!

**Comment by julienschmidt** [comment]
The Mobile Crawler actually seems to work a lot better than the regular REST Search API. 
While I get rate limited after just a few queries with the Search API, I just crawled a **complete** :tada: dataset of Walder Frey (20665 Tweets, searched just for exact matches of "Walder Frey") without being rate-limited even once :+1: 

While it will take days to crawl all characters, we now can at least crawl datasets for specific characters with which we can work then. Here is an example from June 2013, that should be enough for interesting charts (note: we crawl blocks of up to 100 tweets each since we need to get additional data from the REST API - which accepts up to 100 IDs):

```
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Sun Jun 30 18:10:49 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Wed Jun 26 10:43:56 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Tue Jun 25 07:25:57 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Thu Jun 20 15:56:59 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Tue Jun 18 07:22:27 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Sun Jun 16 22:37:38 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Fri Jun 14 19:01:43 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Fri Jun 14 04:25:01 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Wed Jun 12 22:34:52 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Tue Jun 11 12:47:03 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Tue Jun 11 02:47:31 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 10 15:48:19 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 10 12:35:43 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 10 01:23:22 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 10 01:20:10 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Sun Jun 09 19:49:33 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Sat Jun 08 20:12:07 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Fri Jun 07 23:09:36 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Fri Jun 07 18:39:44 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Thu Jun 06 16:47:40 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Thu Jun 06 03:47:58 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Wed Jun 05 17:47:51 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Wed Jun 05 14:54:57 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Wed Jun 05 09:52:01 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Tue Jun 04 23:49:56 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Tue Jun 04 20:12:48 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Tue Jun 04 15:44:10 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Tue Jun 04 09:56:31 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Tue Jun 04 09:45:09 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Tue Jun 04 03:58:15 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Tue Jun 04 00:18:06 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 23:05:00 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 21:38:22 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 20:58:17 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 20:14:16 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 17:53:36 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 17:06:14 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 15:16:32 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 14:16:44 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 12:47:11 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 10:28:32 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 05:28:41 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 04:58:27 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 03:52:36 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 03:12:38 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 02:14:37 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 01:56:25 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 01:17:25 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 01:12:59 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Mon Jun 03 01:08:34 +0000 2013
[crawler/mobile] 56ea4cff8c27d7c637505d96 { found: 100, inserted: 100 } Sat Jun 01 04:11:10 +0000 2013
```

**Comment by julienschmidt** [comment]
Guys, it has been 20 hours again already... press the god damn "Merge pull request" buttons or comment on the code...

**Comment by sacdallago** [comment]
:D @julienschmidt :D :D

**Pull request merged**
