### PR TITLE
meh

### PR DESCRIPTION
**Pull request by julienschmidt**
See #56

### CODE REVIEW

**Comment by julienschmidt** [comment]
WIP means Work-In-Progress... as in do-not-merge-yet

**Comment by marcusnovotny** [comment]
Wasn't aware, do you want me to revert it?

**Comment by julienschmidt** [comment]
undone already, but I can't reopen this PR :disappointed:

**Comment by marcusnovotny** [comment]
Mea culpa. Thanks for bearing with me... Learning a little more every day :sweat_smile:

**Pull request merged**
