### PR TITLE
Visualization: Hourly CSV API

### PR DESCRIPTION
**Pull request by marcusnovotny**
Couldn't stop working on #71. Not having the hourly CSV API really bugged me

I managed to implement it today and it runs super smooth on all browsers I've tried. @julienschmidt @santanumohanta could please try and tell me if you like it? It would be amazing if we could still include it.

There's only one bug, namely that d3js throws path errors in the console when loading 2 months of which 1 is completely empty. However, it doesn't interfere with functionality at all. No idea why it's happening atm, but I'm confident that I can get rid of this minor issue too.

<s>Oh my god that came from the lint errors, I'm dying. It's fully functional now and could be integrated on the spot. This would also be the last update then to not stress out @CavidSalahov</s> Nope, still happening, only in Chrome though. Weird

Daily Data

Hourly Data

The transition is animated & all, it's super fancy. :smile: 
This is a minor character btw, still having trouble with Jon Snow so I couldn't test on him, but it should look amazing there. If one of you has characters with a lot of data, please try and let me know!

@sacdallago Do you already have a running copy of our app? You're welcome to try it too!

### CODE REVIEW

**Comment by gyachdav** [comment]
I know the feeling when you become OCD about a feature :smile: 

I thought about cloning your app and test it out, however creating a twitter key and other reqs is a turnoff. Is there a demo site you can quickly set up?

**Comment by marcusnovotny** [comment]
Sorry I have no hosting capabilities :disappointed:

**Comment by julienschmidt** [comment]
I can set up a static version of the frontend.

**Comment by gyachdav** [comment]
What is a static version of the front end?

**Comment by sacdallago** [comment]
I have hosting capabilities! I'd be more then happy to host it somewhere on the got.show server an domain, if you instruct me on how to!

**Comment by julienschmidt** [comment]
Our backend (crawler / aggregator) basically just generates static CSV files very every character. Only the overview page is dynamically generated.
Basically I would just dump the generated CSVs + saved copies of the otherwise dynamically generated pages on my server (without the backend for updates).

**Comment by gyachdav** [comment]
cool that would be great. hope it's stable enough so i can demo.

**Comment by sacdallago** [comment]
Oh, no need to host it on your machine @julienschmidt 
Just let me know how I can `wget` the CSVs and I can put it on the server, the same way I put the tiles on http://tiles.got.show

:wink:

**Comment by julienschmidt** [comment]
@sacdallago 
If you want to run the regular ("dynamic") version:
1) Read the README
.
.
.
.
.
.
.
Alternatively:
1) [Generate Twitter API  key](https://apps.twitter.com/)
2) Clone repo
3) Install and start MongoDB
4) run `npm install`
5) cd example/app
6) cp config.json.sample config.json
7) ed config.json *
8) node app
9) wait

*: nano / pico / vi / vim / emacs might also work

**Comment by julienschmidt** [comment]
Cool. Someone changed the _id of characters in the API again :unamused:

**Comment by marcusnovotny** [comment]
They see me crawling, they hating :notes:

**Comment by sacdallago** [comment]
The second thing was what I was looking for.
I got about 1 million things to read and do guys, so it's hard to put myself down and go through your very, very well written readme, but too long for someone with a 1 minute attention span :laughing: 

Can I use the same Twitter keys I use for the API of project A? Or should I generate new keys for a "new app".. I remember someone rising this point, I don't remember if it was your group or the otherone.

And to your last point: I had to refill the characters collection today. I told you this may happen very often :) so how do I solve this problem on your side?

**Comment by julienschmidt** [comment]
[Update + insert](http://lmgtfy.com/?q=mongodb+upsert) characters, instead of recreating the DB from scratch every time :stuck_out_tongue_closed_eyes:

**Comment by sacdallago** [comment]
I didn't implement the scrapers @julienschmidt :D trust me. I know how to do my job :laughing:

**Comment by gyachdav** [comment]
@julienschmidt we work with what we have not what we dont have. This is the maintenance procedure  we got from project A and thats what we will have to use until further notice. I believe you were given the tip to not rely on internal IDs but yet you did so now we have a problem...

**Comment by julienschmidt** [comment]
We don't have a problem either. Our package works very fine.

If the maintenance plan is to drop the DB every time and start from scratch, then that is fine with us. Just don't forget do drop our database on every update too, since our DB was actually designed for consistency and **durability**.

**Comment by gyachdav** [comment]
Honestly I dont see how using a foreign key as an internal ID is a durable solution..

**Comment by sacdallago** [comment]
It's not drops, it's refills :wink: and refills overwrite the data by dropping and rewriting, because sometimes there is erroneous data (like houses being interpreted as characters by the scraper, or fields in the data that should not be there). It could have been done better, don't tell me, but that's how it is.
And yes.. using foreign keys of an entirely different database is not the smartest choice either.
I would have used the slugs, or MD5 hashes, or the name of the character which anyway is a key and unique ;)
How much of a hassle would it be to fix this? You understand that this poses some real problem in the long run...

**Comment by julienschmidt** [comment]
Just some suggestions for the next seminar:
- Make clear that one may not assume that all people, especially those who are in charge of the DB, have fully understood ACID yet
- Make clear from day 1 if a project is going to have a separate DB or if our DB gets merged in the main DB

**Comment by gyachdav** [comment]
Duly noted, thanks!

**Comment by sacdallago** [comment]
Ok so, app is running, I'll expose it now, quick question: how normal is this?

``` bash
[main][INFO] Starting update loop...
server running on port 3020
[main][ERROR] { [Error: connect ECONNREFUSED 131.159.28.95:443]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '131.159.28.95',
  port: 443 }
[main][ERROR] { [Error: connect ECONNREFUSED 131.159.28.95:443]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '131.159.28.95',
  port: 443 }
[core/db][INFO] connected.
```

:joy:

**Comment by julienschmidt** [comment]
I guess that is from the Characters / Episodes update.
That's just the error node reports on requests. Either the server at 131.159.28.95:443 is actually refusing connections or there is a firewall or some other reason why node cannot connect to the server.

**Comment by sacdallago** [comment]
Annnnddd should I be worried or something?
I am actually servicing port 3020 on http://csv.got.show but nginx is plain complaining. Is this normal?
I was about to read the code in the example app to figure it out but you are quicker :D

**Comment by julienschmidt** [comment]
Are you trying to reverse proxy it with nginx or how does nginx fit into the setup?

**Comment by sacdallago** [comment]
Reverse proxy!

**Comment by sacdallago** [comment]
I only have 80 and 443 open on that machine, so there's not much of a solution there :D

**Comment by julienschmidt** [comment]
Is 131.159.28.95 the same machine? If yes, how about you use `localhost` instead (set `cfg.api.https` to `false`)

**Comment by sacdallago** [comment]
But even if I use a SOCKS proxy, forward localhost and go to 3020 I end up in a redirect to `https://www.localhost.com:3020/` and a `server not found` error

**Comment by sacdallago** [comment]
Yes, same machine! Ok... Will do that

**Comment by julienschmidt** [comment]
Don't forget to change to port too

**Comment by sacdallago** [comment]
Wait, wait. Where should I change this?
In config.json I only have (xxx is obviously set in my case):

``` javascript
{
    "port": 3020, 
    "gotsent": {
        "mongodb": {
            "uri": "xxx"
        },
        "twitter": {
            "access_token": "xxx",
            "access_token_secret": "xxx",
            "consumer_key": "xxx",
            "consumer_secret": "xxx"
        }
    }
}
```

**Comment by julienschmidt** [comment]
``` js
{
    "port": 3020, 
    "gotsent": {
        "mongodb": {
            "uri": "xxx"
        },
        "api": {
                "https": false,
                "host": "localhost:3019",
                "prefix": "/api/"
         },
        "twitter": {
            "access_token": "xxx",
            "access_token_secret": "xxx",
            "consumer_key": "xxx",
            "consumer_secret": "xxx"
        }
    }
}
```

No guarantees.

**Comment by sacdallago** [comment]
19? :D are you trying to lure me into madness?

**Comment by sacdallago** [comment]
AAAAHH!!! all clear. It's 10! :D I always 10-separate executions, it's easier to remember and I like x0x0 ports :joy:

**Comment by sacdallago** [comment]
It doesn't like me putting the port number I guess!

``` bash
[main][ERROR] { [Error: getaddrinfo ENOTFOUND localhost:3010 localhost:3010:80]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'localhost:3010',
  host: 'localhost:3010',
  port: 80 }
```

notice the `localhost:3010:80`

**Comment by julienschmidt** [comment]
mkay, needs another cfg option then...

**Comment by sacdallago** [comment]
It's good that we notice this now anyway.. The moment **F** is gonna ship their package to us, just imagine the mess that this "bug" would have caused :joy: I would have gone :nut_and_bolt:

**Comment by julienschmidt** [comment]
#111 for the port

**Comment by julienschmidt** [comment]
And regarding the other issue: #112

**Comment by sacdallago** [comment]
Nice! Now I get new errors :dancer: but we are moving forward:

with https:

``` javascript
[main][INFO] Starting update loop...
server running on port 3020
[main][ERROR] { [Error: Hostname/IP doesn't match certificate's altnames: "IP: 127.0.0.1 is not in the cert's list: "]
  reason: 'IP: 127.0.0.1 is not in the cert\'s list: ',
  host: '127.0.0.1',
  cert: 
   { subject: { CN: 'api.got.show' },
     issuer: 
      { C: 'US',
        O: 'Let\'s Encrypt',
        CN: 'Let\'s Encrypt Authority X1' },
     subjectaltname: 'DNS:api.got.show, DNS:got.show, DNS:www.got.show',
     infoAccess: { 'OCSP - URI': [Object], 'CA Issuers - URI': [Object] },
     modulus: 'BE2CC6290BD0ACC4C649957E5BD2A18AFDEB75415626281B991EE6B3A8ADD68231E0D512FE996BF031B46ADE48B29356E370F534DF562FF9559E738B33D7E5A8D9F5DE277099E5B1D1C8E777A40A63DCAB3706530A8A371921C372557CC8AA87F22F545287F13299EA46884A007AF7E45156C57322F056846AF975F0D659428282A9B820CA7599E674C2BEAFA33CDC3062FAEFD5CCC2FCE5CFF87A29444849248E13830B96CDE9A2792825EC42D8FD82C7ACD6227D0464E2981BF24CE8787674E8AC0760174CBF1A2BDA548D8B4506B658542ACBFA9EBAB3F9BB792DF170A8919852DF2D43AF87F0795E3B74B6A52105E2373F06EFD043EF4887E860D5CB3EE1',
     exponent: '0x10001',
     valid_from: 'Mar 23 12:22:00 2016 GMT',
     valid_to: 'Jun 21 12:22:00 2016 GMT',
     fingerprint: '35:1B:24:84:2E:7E:7A:D9:BE:23:17:D8:6F:2D:56:61:92:08:4C:5C',
     ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],
     serialNumber: '0195CBFE4AAC24447C6D55FCA63823508071',
     raw: <Buffer 30 82 05 14 30 82 03 fc a0 03 02 01 02 02 12 01 95 cb fe 4a ac 24 44 7c 6d 55 fc a6 38 23 50 80 71 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 4a ... > } }
[main][ERROR] { [Error: Hostname/IP doesn't match certificate's altnames: "IP: 127.0.0.1 is not in the cert's list: "]
  reason: 'IP: 127.0.0.1 is not in the cert\'s list: ',
  host: '127.0.0.1',
  cert: 
   { subject: { CN: 'api.got.show' },
     issuer: 
      { C: 'US',
        O: 'Let\'s Encrypt',
        CN: 'Let\'s Encrypt Authority X1' },
     subjectaltname: 'DNS:api.got.show, DNS:got.show, DNS:www.got.show',
     infoAccess: { 'OCSP - URI': [Object], 'CA Issuers - URI': [Object] },
     modulus: 'BE2CC6290BD0ACC4C649957E5BD2A18AFDEB75415626281B991EE6B3A8ADD68231E0D512FE996BF031B46ADE48B29356E370F534DF562FF9559E738B33D7E5A8D9F5DE277099E5B1D1C8E777A40A63DCAB3706530A8A371921C372557CC8AA87F22F545287F13299EA46884A007AF7E45156C57322F056846AF975F0D659428282A9B820CA7599E674C2BEAFA33CDC3062FAEFD5CCC2FCE5CFF87A29444849248E13830B96CDE9A2792825EC42D8FD82C7ACD6227D0464E2981BF24CE8787674E8AC0760174CBF1A2BDA548D8B4506B658542ACBFA9EBAB3F9BB792DF170A8919852DF2D43AF87F0795E3B74B6A52105E2373F06EFD043EF4887E860D5CB3EE1',
     exponent: '0x10001',
     valid_from: 'Mar 23 12:22:00 2016 GMT',
     valid_to: 'Jun 21 12:22:00 2016 GMT',
     fingerprint: '35:1B:24:84:2E:7E:7A:D9:BE:23:17:D8:6F:2D:56:61:92:08:4C:5C',
     ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],
     serialNumber: '0195CBFE4AAC24447C6D55FCA63823508071',
     raw: <Buffer 30 82 05 14 30 82 03 fc a0 03 02 01 02 02 12 01 95 cb fe 4a ac 24 44 7c 6d 55 fc a6 38 23 50 80 71 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 4a ... > } }
```

which is.. ok! Because I didn't put the ip address in the certificate. So: crap. But the server should be running on http (with socks on http://localhost:3010 I get the right thing), buuuut:

``` javascript
[main][INFO] Starting update loop...
server running on port 3020
[main][ERROR] { status: 502,
  data: '<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.4.6 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n' }
[main][ERROR] { status: 502,
  data: '<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.4.6 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n' }
```

:sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob: :sob:

**Comment by julienschmidt** [comment]
And regarding the other issue: #112
Drop the mongodb  afterwards.

@sacdallago No idea what's going on there. I'd suggest you keep it internal and access port 3010 directly (without TLS, right?)

**Comment by sacdallago** [comment]
Yeah.. I'm gonna try a `curl` now because WTF.

```
"api": {
                "https": false|true,
                "host": "localhost"|"127.0.0.1",
        "port": "3010",
                "prefix": "/api/"
         },
```

**Comment by sacdallago** [comment]
And yes, `curl http://localhost:3010/api/characters` returns what it should. No fucking idea.

**Comment by sacdallago** [comment]
Damn. I'm way too far beyond my cognitive capabilities to have a look at this now. It's deferred to tomorrow.

**Comment by sacdallago** [comment]
I got it working with some hokus pokus. Had to code your app.js but, hey.. I'm still good at this shit?!

``` bash
[main][INFO] Starting update loop...
server running on port 3020
[main][INFO] Episodes updated
[core/db][INFO] connected.
[crawler/blacklist][WARN] filtered unclassified: Helya
[crawler/blacklist][WARN] filtered unclassified: Qyburn
[crawler/blacklist][WARN] filtered unclassified: S'vrone
[crawler/blacklist][WARN] filtered unclassified: Tickler
[crawler/blacklist][WARN] filtered unclassified: Weepe
```

http://csv.got.show

@gyachdav

**Comment by sacdallago** [comment]
```
[crawler/mobile] Yellow Dick found: 100 inserted: 100 2013-06-24 10:38:20
```

This guy still there? :laughing:

**Comment by marcusnovotny** [comment]
Apparently :smile: Let's get rid of him.

Thanks for setting it up, super interesting for testing! Noticed zooming doesn't work on mobile :angry:

**Comment by julienschmidt** [comment]
#115

**Pull request merged**
