### PR TITLE
Dick Move

### PR DESCRIPTION
**Pull request by julienschmidt**
aaand-hes-gone

### CODE REVIEW

**Comment by julienschmidt** [comment]
One further question: Why was there so much hate for yellow dicks on Monday Feb. 07, 2011?

**Comment by sacdallago** [comment]
:D Are you sure you want to find out?
It probably has very little to do with GoT and very much with a yellow dick

**Comment by sacdallago** [comment]
P.S.: I pulled and restarted the process. So the code is at the latest version.

I didn't need to drop the db, right? This morning I was running yesteray's 12am latest version

**Comment by julienschmidt** [comment]
There were changes to the DB layout at 1:26 AM (#113).
Also you would have to manually remove the "Yellow Dick" documents (`db.charactersentiments.deleteOne({name: "Yellow Dick"}`, same for the tweets).

I'd drop it.

**Comment by sacdallago** [comment]
Do I drop everything? Is that what you are trying to say? :D

**Comment by sacdallago** [comment]
I mean, it's only up since about an hour anyway, so, no big deal!

**Comment by julienschmidt** [comment]
drop it

**Pull request merged**
