### PR TITLE
Configured deploy to npm

### PR DESCRIPTION
**Pull request by jsalahov**

### CODE REVIEW

**Comment by julienschmidt** [comment]
1) No need to reformat all the existing files. Now you're also using a mix of 2-spaces and 4-spaces indentation.
2) The proposed name was gotsentiment**al**

**Comment by sacdallago** [comment]
also: saving a key on an open source repository? are you crahahahazy?

**Comment by jsalahov** [comment]
The key is encrypted

**Comment by jsalahov** [comment]
And goddamn this autoformat :angry:

**Comment by julienschmidt** [comment]
I don't think autoformat uses 2-spaces and 4-spaces at the same time...
But you should consider to kill the plugin anyway

**Comment by jsalahov** [comment]
it is configured for 4 spaces, don't know what happens there, but oh, that plugin will pay :smiling_imp:

**Comment by jsalahov** [comment]
Found the bugger, it was travis itself that modified the whitespaces. Plugin was innocent :relaxed:

**Pull request closed without merging**
