### PR TITLE
Make jshint fail on warning. Resolves #30

### LINKED ISSUE #30: Gulp: Lint not enforced
Currently warnings by jshint are not treated as errors and therefore don't let the test fail.

We're strict here, please change the behavior so that warnings are treated as errors :smiling_imp:

### PR DESCRIPTION
**Pull request by jsalahov**

### CODE REVIEW

**Comment by jsalahov** [comment]
Travis fails because #34 hasn't been merged yet

**Comment by julienschmidt** [comment]
Use "Fixes" instead of "Resolves" in a new line, then the related issue is automatically closed :wink:

**Comment by jsalahov** [comment]
It is not just "Fixes" any form of "fix/close/resolve" should work. Also not sure about newline, I think it should just appear anywhere in commit message
https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by julienschmidt** [comment]
Resolves in the same line didn't work :stuck_out_tongue_winking_eye:

**Comment by jsalahov** [comment]
That is strange :confused:  Because it worked here:
https://github.com/Rostlab/JS16_ProjectB_Group6/issues/4
Maybe it is just case-sensitive?

**Pull request merged**
