### PR TITLE
crawler: get characters and basic twitter integration

### PR DESCRIPTION
**Pull request by julienschmidt**
@santanumohanta here is my progress on the crawler/twitter part
It really seems like it is a limitation of the twitter API that we can't get results older than 7 days 😟

### CODE REVIEW

**Comment by julienschmidt** [comment]
I use the `config.json` now. Insert your twitter key / token / secrets there.
Then run with `$ node crawler.js`

**Comment by gyachdav** [comment]
Are you guys aware that project A is also implementing a Twitter API? Can you join forces with them to get the data?

**Comment by julienschmidt** [comment]
Their implementation does not really help us. It isn't easier to use, it is just another REST API again. Moreover there are rather low limits which are easily exceeded when we try to get millions (?) of tweets, so we need our own API keys anyway. Also they currently use the streaming API only. We need the twitter "archive" instead.

**Comment by julienschmidt** [comment]
> The Twitter Search API searches against a sampling of recent Tweets published in the past 7 days.

https://dev.twitter.com/rest/public/search

Manually setting a date like `until: '2016-01-30'` doesn't work either. It seems like we can only analyze future tweets (and tweets from the last week), not tweets of all seasons :disappointed:

**Comment by julienschmidt** [comment]
It seems to be a recent change in the API: https://twittercommunity.com/t/search-api-sampling-what-kind-of-sampling/61190
So basically we also have no idea how representative those tweets are - they are just a sample.

**Comment by julienschmidt** [comment]
The characters part is now also ready. Unfortunately the data provided by the API is not duplicate-free. For example:

``` js
{ title: 'Ser',
  name: 'Abelar Hightower',
  _id: '56d912fb1e3cd5e6474a273d',
  __v: 0,
  updatedAt: '2016-03-04T04:45:47.300Z',
  createdAt: '2016-03-04T04:45:47.300Z',
  skills: [] }
{ title: 'Ser',
  name: 'Abelar Hightower',
  _id: '56d913b51e3cd5e6474a2f1c',
  __v: 0,
  updatedAt: '2016-03-04T04:48:53.702Z',
  createdAt: '2016-03-04T04:48:53.702Z',
  skills: [] }
```

Some of the updates therefore fail (our database does not allow duplicates). 
The issue is known to group A already: https://github.com/Rostlab/JS16_ProjectA/issues/40

**Pull request merged**
